[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # Esta variable le dice a Netlify que no intente detectar automáticamente el framework
  # y que no use el runtime de Next.js.
  # Es una variable interna de Netlify para forzar el comportamiento.
  NETLIFY_BUILD_DISABLE_FRAMEWORK_DETECTION = "true"